[line_break]
disabled = true

[cmd_duration]
disabled = true

[character]
success_symbol = '[\\$>](bold green)'
error_symbol = '[\\$>](bold red)'
vicmd_symbol = '[\\$<](bold blue)'

[username]
disabled = true

[hostname]
ssh_only = true
format =  '[$hostname](bold white) '
disabled = false

[kubernetes]
format = '[⛵ $context \($namespace\)](dimmed green) '
disabled = false

[aws]
symbol = ' '

[battery]
full_symbol = ''
charging_symbol = ''
discharging_symbol = ''

[conda]
symbol = ' '

[dart]
symbol = ' '

[directory]
read_only = ' '
style = 'bold green'

[docker]
symbol = ' '

[elixir]
symbol = ' '

[elm]
symbol = ' '

[git_branch]
symbol = ' '

[golang]
symbol = ' '

[haskell]
symbol = ' '

[hg_branch]
symbol = ' '

[java]
symbol = ' '

[julia]
symbol = ' '

[memory_usage]
symbol = ' '

[nim]
symbol = ' '

[nix_shell]
symbol = ' '

[nodejs]
symbol = ' '

[package]
symbol = ' '

[perl]
symbol = ' '

[php]
symbol = ' '

[python]
symbol = ' '

[ruby]
symbol = ' '

[rust]
symbol = ' '

[swift]
symbol = 'ﯣ '

